### ISSUE TITLE
[feature request] Keep all classes with html attributes ( for tailwind css )

### ISSUE THREAD

**Issue by ausir0726** [dimensi/xhtml2pug#13]
Hi, 
I look for a while for vue to pug
especially for case sensitive convert.
It's a epic work.

but when I work with Tailwind CSS
it have another issue like
```html
<div class="m-[50px] -p-10 sm:p-5"><h1>test</h1></div>
```

it's converted
```pug
.m-[50px].-p-10.sm:p-5
  h1 test
```
but it's a illegal class literal  for pug

so when it work with Tailwind CSS
it sholud be covert to
```pug
div(class="m-[50px] -p-10 sm:p-5")
  h1 test
```
that will keep every atom css class will be correct
and don't need any class literal 

I make PR for this feature
please check it.

**Comment by dimensi** [comment]
Well, I'll be wait your PR 😀

**Comment by ausir0726** [comment]
here have some Tailwind UI compoent html code for understading .

thanks.

https://tailwindui.com/components/application-ui/data-display/description-lists

**Comment by ausir0726** [comment]
seems like `-i, --inlineCSS` is the same feature

I didn't understand `inlineCSS` meaning correctly
