### ISSUE TITLE
Shouldn't convert special characters inside template braces

### ISSUE THREAD

**Issue by geoidesic** [dimensi/xhtml2pug#6]
Double braces `{{ }}` are pretty much an HTML templating standard. Whatever's in them should be interpreted within the JavaScript context, rather than the HTML context.

e.g.
```
<p>{{ $t('sso.form.registrationComplete') }}</p>
```
... currently is converted to this:
```
p {{  $t(&apos;sso.form.registrationComplete&apos;)  }}
```
... when the expectation would be this
```
p {{ $t('sso.form.registrationComplete') }}
```

**Comment by dimensi** [comment]
Hi, you need to disable a `encode` option to get expected result.
https://github.com/dimensi/xhtml2pug/blob/main/README.md?plain=1#L100

**Comment by geoidesic** [comment]
How would I do that within the context of doing the conversion within your Vue Extension?

**Comment by dimensi** [comment]
![image](https://user-images.githubusercontent.com/11390039/166916652-0f5e731d-7214-4c9d-9822-face873f6544.png)

**Comment by geoidesic** [comment]
I don't seem to have any settings:

<img width="1680" alt="Screenshot 2022-05-10 at 15 27 24" src="https://user-images.githubusercontent.com/4637995/167652572-fdeb0c34-bea5-4cff-b0fb-caff4f9687db.png">

**Comment by geoidesic** [comment]
Thoughts?

**Comment by geoidesic** [comment]
I had another look today and for some reason all the settings turned up. For this example it works as you say.

**Comment by dimensi** [comment]
I'm glad it fixed itself :)
