### ISSUE TITLE
Un-parsable conversion: multi-line attribute quotations

### ISSUE THREAD

**Issue by geoidesic** [dimensi/xhtml2pug#7]
This HTML:

```
<q-checkbox
    v-if="who == 3"
    label="Framework agreement"
    :value="terms.attributes.frameworkAgreement"
    @input="
      (val) => {
        $set(terms.attributes, 'frameworkAgreement', val)
      }
    "
    :disable="readonly"
></q-checkbox>
```
Even using the Vue settings; gets converted to something that Vetur can't format:

```
    q-checkbox(v-if="who == 3" label='Framework agreement' :value="terms.attributes.frameworkAgreement" @input="
            (val) => {
              $set(terms.attributes, 'frameworkAgreement', val)
            }
          " :disable="readonly")
```
It should imho output this:
```
q-checkbox(
  v-if="who == 3",
  label="Framework agreement",
  :value="terms.attributes.frameworkAgreement",
  @input="(val) => { $set(terms.attributes, 'frameworkAgreement', val); }",
  :disable="readonly"
)
```
i.e. multi-line attribute quotatations should be converted to a single line.

**Comment by dimensi** [comment]
Well, I will think what I can do there

**Comment by geoidesic** [comment]
Anything I can help with? Keen to get this working.

**Comment by dimensi** [comment]
Sorry, I was busy with work and forgot about this. I will look on this in weekends.

**Comment by dimensi** [comment]
So, I updated the logic with the attribute renderer. Now if there are transitions to the next line, I wrap the attribute in back quotes 
<img width="2177" alt="image" src="https://user-images.githubusercontent.com/11390039/174496797-4ba6055d-bf4d-4b18-95ce-eba099a2ea74.png">

It's easer maintain then inline multiline

**Comment by dimensi** [comment]
@geoidesic ?

**Comment by geoidesic** [comment]
Yes, that seems to work. Tx!

**Comment by geoidesic** [comment]
Although see #18
